# --> check the technical writing for various characteristics
- writing/reflection.md:
  - description: Ensure that reflection.md file exists in the writing/ directory
    check: ConfirmFileExists
  # - description: Write a minimum number of meaningful words (adding around 100 words in total) in the reflection
  #   check: CountFileWords
  #   options:
  #     count: 500
  #     exact: false
  - description: Complete all TODOs, remove the TODO markers in writing/reflection.md
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in writing/reflection.md
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true

# --> check the code for various characteristics
- ./assignments/number_guessing_game/main.py:
  - description: Ensure that ./assignments/number_guessing_game/main.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./assignments/number_guessing_game/main.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./assignments/number_guessing_game/main.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true
- ./assignments/number_guessing_game/game_logic.py:
  - description: Ensure that ./assignments/number_guessing_game/game_logic.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./assignments/number_guessing_game/game_logic.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./assignments/number_guessing_game/game_logic.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true


- ./assignments/palindrome_checker/main.py:
  - description: Ensure that ./assignments/palindrome_checker/main.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./assignments/palindrome_checker/main.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./assignments/palindrome_checker/main.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true
- ./assignments/palindrome_checker/palindrome.py:
  - description: Ensure that ./assignments/palindrome_checker/palindrome.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./assignments/palindrome_checker/palindrome.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./assignments/palindrome_checker/palindrome.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true


- ./assignments/prime_finder/main.py:
  - description: Ensure that /assignments/prime_finder/main.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./assignments/prime_finder/main.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./assignments/prime_finder/main.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true
- ./assignments/prime_finder/prime_utils.py:
  - description: Ensure that ./assignments/prime_finder/palindrome.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./assignments/prime_finder/prime_utils.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./assignments/prime_finder/prime_utils.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true

- ./assignments/quadratic_solver/main.py:
  - description: Ensure that ./assignments/quadratic_solver/main.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./assignments/quadratic_solver/main.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./assignments/quadratic_solver/main.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true
- ./assignments/quadratic_solver/quadratic.py:
  - description: Ensure that ./assignments/quadratic_solver/quadratic.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./assignments/quadratic_solver/quadratic.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./assignments/quadratic_solver/quadratic.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true

- ./assignments/extra_challenge/main.py:
  - description: Ensure that ./assignments/extra_challenge/main.py file exists
    check: ConfirmFileExists
  - description: Complete all TODOs, remove the TODO markers in the File ./assignments/extra_challenge/main.py
    check: MatchFileFragment
    options:
      fragment: TODO
      count: 0
      exact: true
  - description: Delete the 'Add Your Name Here' prompt in the File ./assignments/extra_challenge/main.py
    check: MatchFileFragment
    options:
      fragment: "Add Your Name Here"
      count: 0
      exact: true










# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (5) in repository
  check: CountCommits
  options:
    count: 5